apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pvc-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/cassandra_data"